# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    restart: always
    ports:
    - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: cwtwodb

  adminer:
    image: adminer
    restart: always
    ports:
      - 8085:8080